name: Frontend CI

on:
  push:
    branches:
    - master
    paths:
    - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/crud-app:frontend-${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq

    - name: Update frontend tag in Helm chart
      run: |
        yq e '.frontend.image.tag = "frontend-${{ github.run_id }}"' -i helm/crud-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "jamiekariuki18@gmail.com"
        git config --global user.name "jamiekariuki"
        git add helm/crud-app-chart/values.yaml
        if git diff --cached --quiet; then
        echo "No changes to commit."
        else
        git commit -m "Update tag in Helm chart [skip ci]"
        git pull --rebase origin master
        git push origin master
        fi
